name: <+service.name>
replicas: 3

image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>

namespace: <+infra.namespace>

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: ClusterIP

sename: <+variable.username>
# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 80
serviceTargetPort: 8000

env:
  config:
    HARNESS_BUILD: <+pipeline.sequenceId>
    SERVICE_NAME: <+service.name>
    APPLICATION_VERSION: <+artifacts.primary.tag>

# Default nodeSelector for GKE deployments
nodeSelector:
  cloud.google.com/gke-nodepool: deploy-pool
