
name: <+service.name>
replicas: 1

image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>

createNamespace: "true"
namespace: <+infra.namespace>

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: ClusterIP

sename: <+variable.username>
# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 8080
serviceTargetPort: 8080

# Default nodeSelector for GKE deployments
nodeSelector:
  cloud.google.com/gke-nodepool: deploy-pool